### Here is an example of a Python code snippet that demonstrates the calculation of mean squared error (MSE) loss

In [25]:
import numpy as np
import sympy as sp

In [14]:
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.1, 2.2, 2.8, 3.9, 5.1])

mse = mean_squared_error(y_true, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.022000000000000023


### Create a Vector

In [17]:
x = np.array([1, 2, 3]) # Create a vector
print("Vector x:", x)

Vector x: [1 2 3]


### Create a Matrix

In [20]:
A = np.array([[1,2,3],[5,6,7]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2 3]
 [5 6 7]]


### Matrix Operations

In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = A + B # Add two matrices
print("Matrix C:\n", C)

D = A - B # Subtract two matrices
print("Matrix D:\n", D)

E = A * B # Multiply two matrices
print("Matrix E:\n", E)

F = A / B # Divide two matrices
print("Matrix F:\n", F)

Matrix C:
 [[ 6  8]
 [10 12]]
Matrix D:
 [[-4 -4]
 [-4 -4]]
Matrix E:
 [[ 5 12]
 [21 32]]
Matrix F:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [22]:
# Matrix multiplication using matmul
G = np.matmul(A, B)
print("Matrix G:\n", G)

# Matrix multiplication using dot
H = np.dot(A, B)
print("Matrix H:\n", H)

# Matrix multiplication using @
I = A @ B
print("Matrix I:\n", I)

Matrix G:
 [[19 22]
 [43 50]]
Matrix H:
 [[19 22]
 [43 50]]
Matrix I:
 [[19 22]
 [43 50]]


In [23]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [31]:
# Define a variable
x = sp.symbols('x')

# Define a function
f = x**2 + 2*x + 1

# Calculate the derivative
derivative = sp.diff(f, x)
print("Derivative of f(x):", derivative)

# Calculate the integral from 0 to 1
integral = sp.integrate(f, (x,0,1))
print("Integral of f(x) from 0 to 1:", integral)


Derivative of f(x): 2*x + 2
Integral of f(x) from 0 to 1: 7/3


In [32]:
x,y = sp.symbols('x y') # Define two variables
f = x**2 + 2*x*y + y**2 # Define a function of two variables

# Calculate the partial derivative with respect to x
partial_derivative_x = sp.diff(f, x)

# Calculate the partial derivative with respect to y
partial_derivative_y = sp.diff(f, y)

print("Partial derivative of f(x,y) with respect to x:", partial_derivative_x)
print("Partial derivative of f(x,y) with respect to y:", partial_derivative_y)

Partial derivative of f(x,y) with respect to x: 2*x + 2*y
Partial derivative of f(x,y) with respect to y: 2*x + 2*y


In [34]:
x,y = sp.symbols('x y') # Define two variables
f = x**2 + 2*y**2 + 3*x*y # Define a function of two variables

# Calculate the gradient
gradient = [sp.diff(f, var) for var in (x, y)]
print("Gradient of f(x,y):", gradient)

# Calculate the Hessian matrix
hessian = sp.hessian(f, (x, y))
print("Hessian matrix of f(x,y):\n", hessian)

Gradient of f(x,y): [2*x + 3*y, 3*x + 4*y]
Hessian matrix of f(x,y):
 Matrix([[2, 3], [3, 4]])
